local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>scf', builtin.current_buffer_fuzzy_find, {})
vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
vim.keymap.set('n', '<leader>saf', builtin.live_grep, {})
vim.keymap.set('n', '<leader>sbf', builtin.buffers, {})
vim.keymap.set('n', '<leader>pO', builtin.oldfiles, {})
vim.keymap.set('n', '<leader>cT', builtin.colorscheme, {})
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', '<leader>ps', function() builtin.grep_string({ search = vim.fn.input("Grep > ") }) end)
